--- 
 model_params:
  additional_features_dimension : Null #Features that carry some information about class-identity; analogous to binding features
  additional_zero_dimensions : Null #Features that carry no information about class-identity; analogous to e.g. an input pixel
  learning_rate : 0.1
  training_epochs : 20
  num_networks : 3 #Number of duplicate networks
  data_size : 2048 #Size of synthetic data-set
  batch_size : 512
  
#See config_BindingCNNs.yaml for more information 
 adversarial_params :
  num_attack_examples : 10
  transfer_attack_setup : False
  estimate_gradients : False
  boundary_attack_iterations : 50
  boundary_attack_log_steps : 100
  perturbation_threshold : 
    L0 : 12
    LInf : 0.3
    L2 : 1.5
  save_images : False